### ISSUE TITLE
[BUG] Some mails are not recognized by the mail scanner

### ISSUE THREAD

**Issue by sebastiangiffhorn** [jonaswinkler/paperless-ng#650] opened 2021-02-27 11:55 UTC
I have some mails that don't show up when the mail checker task runs:

The log output is the following:

[2021-02-27 12:41:47,652] [DEBUG] [paperless_mail] Account paperless@giffhorn-net.de: Processing 1 rule(s)
[2021-02-27 12:41:47,664] [DEBUG] [paperless_mail] Rule paperless@giffhorn-net.de.Paperless-Mail: Selecting folder INBOX
[2021-02-27 12:41:47,701] [DEBUG] [paperless_mail] Rule paperless@giffhorn-net.de.Paperless-Mail: Searching folder with criteria (SINCE 4-Jun-2018)
[2021-02-27 12:41:50,574] [DEBUG] [paperless_mail] Rule paperless@giffhorn-net.de.Paperless-Mail: Processed 0 matching mail(s)
[2021-02-27 12:41:50,585] [DEBUG] [paperless_mail] Rule paperless@giffhorn-net.de.Paperless-Mail: Running mail actions on 0 mails

However there are clearly Mails with attachments in this INBOX which match the criteria:

<img width="2610" alt="Bildschirmfoto 2021-02-27 um 12 47 11" src="https://user-images.githubusercontent.com/47003600/109386321-3322ae00-78fa-11eb-9a44-cde29ad87941.png">

The attachment/file itself is working fine. If I use the file and send it in another mail to the Mail-Account, it is picked up properly. So it seems that the original attachment/mail format could be the cause for this.

I could export and send sample mails, however I don't want to upload them here to be publicly available.

**Comment by jonaswinkler** [comment] 2021-03-14 14:55
Probably a duplicate of #404.

**Closed by jonaswinkler** 2021-03-14 14:55 UTC
