### ISSUE TITLE
[BUG] Consumer crashes when using brackets for matching.

### ISSUE THREAD

**Issue by Mech4711** [jonaswinkler/paperless-ng#605] opened 2021-02-23 09:13 UTC
Describe the bug
PDF upload failed

To Reproduce
- Go to self hosted paperless-ng's site
- try to upload the PDF via drag and drop

Expected behavior
- PDF uploaded

Relevant information
Error Message:
![grafik](https://user-images.githubusercontent.com/77811716/108821843-82957100-75be-11eb-808c-4b523004cb95.png)
Version: Paperless-ng 1.1.4 

I have "data" and "media" stored on a mount on a second drive

**Comment by jonaswinkler** [comment] 2021-02-23 09:22
Please use the Bug issue template next time, I need more info for this. 

- Go to the logs and post any related errors from there.
- Post your configuration.

**Comment by Mech4711** [comment] 2021-02-23 09:57
Sorry, i’m new to GitHub. I searched at "Questions? Something not working?" On the main page and found no Template. 

LOG:
```
[2021-02-23 09:02:18,915] [DEBUG] [paperless.consumer] Generating thumbnail for Rechnung R-20475258.pdf...
[2021-02-23 09:02:18,923] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-upload-lw2kla48[0] /tmp/paperless/paperless-9eq_b2j4/convert.png
[2021-02-23 09:02:19,914] [DEBUG] [paperless.parsing.tesseract] Execute: optipng -silent -o5 /tmp/paperless/paperless-9eq_b2j4/convert.png -out /tmp/paperless/paperless-9eq_b2j4/thumb_optipng.png
[2021-02-23 09:02:23,920] [DEBUG] [paperless.consumer] Saving record to database
[2021-02-23 09:02:23,932] [DEBUG] [paperless.matching] DocumentType Rechnung matched on document 2021-02-10 Rechnung R-20475258 because it contains this word: Rechnung
[2021-02-23 09:02:23,933] [DEBUG] [paperless.matching] DocumentType Hausaufgabenbrief matched on document 2021-02-10 Rechnung R-20475258 because it contains this word: die
[2021-02-23 09:02:23,943] [ERROR] [paperless.consumer] The following error occured while consuming Rechnung R-20475258.pdf: missing ), unterminated subpattern at position 28
[2021-02-23 09:02:23,944] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-9eq_b2j4
[2021-02-23 09:12:00,809] [INFO] [paperless.consumer] Consuming Korrektur_ET119339.pdf
[2021-02-23 09:12:00,812] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2021-02-23 09:12:00,821] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2021-02-23 09:12:00,826] [DEBUG] [paperless.consumer] Parsing Korrektur_ET119339.pdf...
[2021-02-23 09:12:01,142] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with {'input_file': '/tmp/paperless/paperless-upload-e1u57ea1', 'output_file': '/tmp/paperless/paperless-jpkpsl94/archive.pdf', 'use_threads': True, 'jobs': 2, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'clean': True, 'skip_text': True}
[2021-02-23 09:12:26,767] [DEBUG] [paperless.consumer] Generating thumbnail for Korrektur_ET119339.pdf...
[2021-02-23 09:12:26,774] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-upload-e1u57ea1[0] /tmp/paperless/paperless-jpkpsl94/convert.png
[2021-02-23 09:12:27,263] [DEBUG] [paperless.parsing.tesseract] Execute: optipng -silent -o5 /tmp/paperless/paperless-jpkpsl94/convert.png -out /tmp/paperless/paperless-jpkpsl94/thumb_optipng.png
[2021-02-23 09:12:29,725] [DEBUG] [paperless.consumer] Saving record to database
[2021-02-23 09:12:29,744] [DEBUG] [paperless.matching] DocumentType Hausaufgabenbrief matched on document 2020-07-15 Korrektur_ET119339 because it contains this word: die
[2021-02-23 09:12:29,745] [DEBUG] [paperless.matching] DocumentType Gehaltsabrechnung matched on document 2020-07-15 Korrektur_ET119339 because it contains this word: der
[2021-02-23 09:12:29,748] [DEBUG] [paperless.matching] DocumentType Meldebescheinigung zur Sozialversicherung matched on document 2020-07-15 Korrektur_ET119339 because it contains this word: zur
[2021-02-23 09:12:29,753] [ERROR] [paperless.consumer] The following error occured while consuming Korrektur_ET119339.pdf: missing ), unterminated subpattern at position 28
[2021-02-23 09:12:29,754] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-jpkpsl94
```

HOST CONFIG:

Host: (VM on Proxmox) 
OS - Debian 10
RAM - 8GB
CPU - 4 Cores 1 Socket (Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz)

I have added 2 Harddrives
scsi0 = NVME 10GB
scsi1 = HDD 500GB

I have installed Debian on the 10GB drive, mounted the HDD at /mnt/hdd and changed the docker compose.yml

```
# docker-compose file for running paperless from the Docker Hub.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# In addition to that, this docker-compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), PostgreSQL is used as the database server.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker-compose pull'.
# - Run 'docker-compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker-compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.

version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: jonaswinkler/paperless-ng:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /mnt/hdd/paperless/data:/usr/src/paperless/data
      - /mnt/hdd/paperless/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: .env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db

volumes:
  data:
  media:
  pgdata:
```

**Comment by jonaswinkler** [comment] 2021-02-23 10:10
No worries.

This looks like you've used regular expressions for one of your tags, correspondents or types, and the regular expression is malformed.

I'll add some form validation to prevent invalid expressions from being entered in the first place.

**Comment by jonaswinkler** [comment] 2021-02-23 11:37
Are you using brackets (`(` and `)`) when matching correspondents / types or tags?

**Comment by Mech4711** [comment] 2021-02-23 12:34
Yes i used brackets in a tag, after i removed them, the upload worked again. Thanks 👍

**Comment by jonaswinkler** [comment] 2021-02-28 21:32
Duplicate of #668

**Closed by jonaswinkler** 2021-02-28 21:32 UTC
Labels: bug
