### ISSUE TITLE
[BUG] Numbers in document overview on tag list and correspondents will not be updated after changing

### ISSUE THREAD

**Issue by Boldie** [jonaswinkler/paperless-ng#898] opened 2021-04-12 11:00 UTC
**Describe the bug**
I noticed the counts of the tags in the search fields will not be updated while tagging the documents.

**To Reproduce**
* Go to the Documents list having a set of documents lets say with Tag "New". The counter next to the Tag is 5
* Update the tags and remove the "New" tag from the 2 documents
* The Tag counter still is at 5 till I reload the page, but it should be 3 now.

**Expected behaviour**
* The Tag counter still is at 5 till I reload the page, but it should be 3 now.

**Screenshots**
N/A

**Relevant information**
 - Host OS of the machine running paperless: Ubuntu 20.04 on Browser side, Ubuntu 18.04 on Host side
 - Browser: Firefox
 - Version 1.4.0
 - Installation method: docker

**Comment by jonaswinkler** [comment] 2021-04-12 12:53
Duplicate of #514

**Closed by jonaswinkler** 2021-04-12 12:53 UTC
