### ISSUE TITLE
Font not found for parser_text

### ISSUE THREAD

**Issue by jovandeginste** [jonaswinkler/paperless-ng#207] opened 2020-12-29 09:40 UTC
When ingesting a number of csv-files, I saw this error come up:

```
| 10:29:39 [Q] ERROR Failed [2014-12-01-554047.csv] - cannot open resource : Traceback (most recent call last):
|   File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
|     res = f(*task["args"], **task["kwargs"])
|   File "/usr/src/paperless/src/documents/tasks.py", line 73, in consume_file
|     override_tag_ids=override_tag_ids)
|   File "/usr/src/paperless/src/documents/consumer.py", line 135, in try_consume_file
|     self.path, mime_type)
|   File "/usr/src/paperless/src/documents/parsers.py", line 235, in get_optimised_thumbnail
|     thumbnail = self.get_thumbnail(document_path, mime_type)
|   File "/usr/src/paperless/src/paperless_text/parsers.py", line 27, in get_thumbnail
|     layout_engine=ImageFont.LAYOUT_BASIC)
|   File "/usr/local/lib/python3.7/site-packages/PIL/ImageFont.py", line 836, in truetype
|     return freetype(font)
|   File "/usr/local/lib/python3.7/site-packages/PIL/ImageFont.py", line 833, in freetype
|     return FreeTypeFont(font, size, index, encoding, layout_engine)
|   File "/usr/local/lib/python3.7/site-packages/PIL/ImageFont.py", line 194, in __init__
|     font, size, index, encoding, layout_engine=layout_engine
| OSError: cannot open resource
```

After investigating, I found that `/usr/share/fonts/liberation/LiberationSerif-Regular.ttf` was hard-coded as the font, but:

```bash
$ docker exec -ti paperless_webserver_1 ls -l /usr/share/fonts/liberation/LiberationSerif-Regular.ttf
ls: cannot access '/usr/share/fonts/liberation/LiberationSerif-Regular.ttf': No such file or directory
```

Furthermore:

```bash
$ docker exec -ti paperless_webserver_1 dpkg -S LiberationSerif-Regular.ttf
fonts-liberation: /usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf
fonts-liberation2: /usr/share/fonts/truetype/liberation2/LiberationSerif-Regular.ttf
```

So:

1. the font has disappeared (and/or moved)?
2. can we make this configurable through `paperless.conf`?

**Comment by jonaswinkler** [comment] 2020-12-29 10:57
Duplicate of #197

Forgot to install the font in the image after updating the thumbnail generation process.

Configuration options sounds reasonable.

**Closed by jonaswinkler** 2020-12-29 10:57 UTC

**Comment by jovandeginste** [comment] 2020-12-29 11:04
> Duplicate of #197

Sorry, totally correct.
