### ISSUE TITLE
Mass-Edit (for tags, document type and correspondent)

### ISSUE THREAD

**Issue by totti4ever** [jonaswinkler/paperless-ng#66] opened 2020-11-29 06:50 UTC
Especially when new to paperless or when introducing new tags or document types, a way to assign a tag/type to multiple documents at the same time would quite very handy.
In the case of setting it up, this might apply also to correspondents.

I could imagine, to enter multi edit mode from the search results and then just providing a drop-down for _add tag_, _remove tag_, _change type_, _change correspondent_ and then select the appropiate. When removing tags of course all tags or at least those which are carried by at least one of the results should be given as choice.

**Comment by jonaswinkler** [comment] 2020-11-29 09:46
Duplicate of #60

**Closed** 2020-11-29 09:46 UTC

**Comment by totti4ever** [comment] 2020-11-29 11:40
Oh sorry, had a look at all issues yesterday morning I think
